<?php

/**
 * @OA\Schema(
 *   schema="HealthProfileMedicalModel",
 *   @OA\Property(
 *       property="symptoms",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   ),
 *   @OA\Property(
 *       property="medicalConditions",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   ),
 *   @OA\Property(
 *       property="autoImmuneDiseases",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   ),
 *   @OA\Property(
 *       property="allergiesCategory",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   ),
 *   @OA\Property(
 *       property="foodIntolerances",
  *      type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   ),
 *   @OA\Property(
 *       property="foodIntolerancesCategory",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   ),
 *   @OA\Property(
 *       property="lifestyleDiet",
  *      type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   ),
 *   @OA\Property(
 *       property="currentMedications",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalTextModel")
 *   ),
 *   @OA\Property(
 *       property="other",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalTextModel")
 *   ),
 *   @OA\Property(
 *       property="healthConcerns",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/medicalTextModel")
 *   ),
 *   @OA\Property(
 *       property="healthGoals",
  *      type="array",
 *       @OA\Items(ref="#/components/schemas/medicalInternalIdModel")
 *   )
 * )
 */
