<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%language}}`.
 */
class m200925_094113_create_language_table extends Migration
{
    public $languages = [
        "Afrikaans",
        "Akan",
        "Albanian",
        "Amharic",
        "Arabic",
        "Armenian",
        "Assamese",
        "Awadhi",
        "Azerbaijani",
        "Azerbaijani (Latin)",
        "Balochi",
        "Bangla (Bangladesh)",
        "Bangla (India)",
        "Basque",
        "Belarusian",
        "Bengali",
        "Bhojpuri",
        "Bosnian (Latin)",
        "Bulgarian",
        "Burmese",
        "Catalan",
        "Cebuano (Visayan)",
        "Central Kurdish (Arabic)",
        "Cherokee",
        "Chewa",
        "Chhattisgarhi",
        "Chinese Simplified",
        "Chinese Traditional",
        "Chittagonian",
        "Croatian",
        "Czech",
        "Danish",
        "Dari",
        "Deccan",
        "Dhundhari",
        "Dutch",
        "Eastern Min (i.e., Fuzhou dialect)",
        "English",
        "Estonian",
        "Filipino",
        "Finnish",
        "French",
        "Fula",
        "Galician",
        "Gan",
        "Georgian",
        "German",
        "Greek",
        "Gujarati",
        "Haitian Creole",
        "Hakka",
        "Haryanvi",
        "Hausa",
        "Hausa (Latin)",
        "Hebrew",
        "Hiligaynon/Ilonggo (Visayan)",
        "Hindi",
        "Hmong",
        "Hungarian",
        "Icelandic",
        "Igbo",
        "Ilocano",
        "Indonesian",
        "Irish",
        "isiXhosa",
        "isiZulu",
        "Italian",
        "Japanese",
        "Javanese",
        "Jin",
        "K'iche'",
        "Kannada",
        "Kazakh",
        "Khmer",
        "Kinyarwanda",
        "Kirundi",
        "KiSwahili",
        "Konkani",
        "Korean",
        "Kurdish",
        "Kyrgyz",
        "Latvian",
        "Lithuanian",
        "Luxembourgish",
        "Macedonian",
        "Madurese",
        "Magahi",
        "Maithili",
        "Malagasy",
        "Malay (i.e., Indonesian and Malaysian)",
        "Malay (Malaysia, Brunei, and Singapore)",
        "Malayalam",
        "Maltese",
        "Mandarin",
        "Maori",
        "Marathi",
        "Marwari",
        "Mongolian (Cyrillic)",
        "Mossi",
        "Nepali",
        "Norwegian (Bokmål)",
        "Norwegian (Nynorsk)",
        "Odia",
        "Odia (Oriya)",
        "Oromo",
        "Pashto",
        "Persian (Farsi)",
        "Polish",
        "Portuguese (Brazil)",
        "Portuguese (Portugal)",
        "Punjabi",
        "Punjabi (Arabic)",
        "Quechua",
        "Romanian",
        "Russian",
        "Saraiki",
        "Scottish Gaelic",
        "Serbian (Cyrillic, Bosnia and Herzegovina)",
        "Serbian (Cyrillic, Serbia)",
        "Serbian (Latin)",
        "Serbo-Croatian",
        "Sesotho sa Leboa",
        "Setswana (South Africa and Botswana)",
        "Shona",
        "Sindhi",
        "Sindhi (Arabic)",
        "Sinhala",
        "Slovak",
        "Slovenian",
        "Somali",
        "Southern Min (i.e., Hokkien and Teochew)",
        "Spanish",
        "Sundanese",
        "Swedish",
        "Sylheti",
        "Tagalog (Filipino)",
        "Tajik (Cyrillic)",
        "Tamil",
        "Tamil (India and Sri Lanka)",
        "Tatar",
        "Telugu",
        "Thai",
        "Tigrinya (Ethiopia)",
        "Turkish",
        "Turkmen",
        "Ukrainian",
        "Urdu",
        "Uyghur",
        "Uzbek",
        "Uzbek (Latin)",
        "Valencian",
        "Vietnamese",
        "Welsh",
        "Wolof",
        "Wu (i.e., Shanghainese)",
        "Xhosa",
        "Xiang",
        "Yoruba",
        "Yue (i.e., Cantonese)",
        "Zhuang",
        "Zulu",
    ];
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%language}}', [
            'id' => $this->primaryKey(),
            'name' => $this->string(),
        ]);

        foreach ($this->languages as $language) {
            $model = new \modules\account\models\ar\Language();
            $model->name = $language;
            $model->save(false);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%language}}');
    }
}
