<?php

use yii\db\Migration;

/**
 * Class m201109_191117_update_insurance_list
 */
class m201114_191117_update_insurance_list extends Migration
{
    public $companiesFromDoc = [
        'UHC Options PPO',
        'UHC Choice Plus POS',
        'UHC Navigate HMO',
        'UHC Navigate POS',
        'Oxford Freedom',
        'BCBS Blue Card PPO',
        'CIGNA PPO',
        'CIGNA Open Access Plus',
        'CIGNA HMO',
        'Oxford Liberty',
        'Aetna Choice POS II',
        'Aetna Signature Administrators PPO',
        'Aetna Managed Choice POS Open Access',
        'Aetna HMO',
        'UHC Compass HMO',
        'Humana Choice POS',
        'Humana ChoiceCare Network PPO',
        'Empire PPO',
        'MVP Preferred PPO',
        'Multiplan PPO',
        'BCBS MA Blue Care Elect PPO',
        'Oxford Metro',
        'CDPHP PPO',
        'Empire HMO',
        'CDPHP New York State of Health - Small Business',
        'Empire Prism EPO Blue Priority',
        'Aetna NYC Community Plan',
        'Aetna Elect Choice EPO',
        'PHCS PPO',
        'Emblem HIP Select PPO',
        'BCBS MA Preferred Blue PPO',
        'Highmark Community Blue PPO',
        'First Health PPO',
        'Fidelis Care NY State of Health HBX',
        'Empire HMO Bronze Individual via Exchange',
        'Aetna Choice POS Open Access',
        'Healthfirst NY HMO ABCD',
        'Healthfirst NY Silver Leaf',
        'Affinity Essential Qualified Health Plans',
        'Horizon PPO',
        'QualCare HMO',
        'Oscar Insurance NY',
        'Horizon Direct Access',
        'Horizon OMNIA',
        'Horizon POS',
        'Horizon HMO',
        'QualCare PPO',
        'Emblem Health Select Care',
        'Horizon Advantage EPO',
        'MetroPlus Health - Exchange',
        'NSLIJ Careconnect',
        'Amerihealth Regional Pref Ntwk HMO HMO + POS',
        'Amerihealth Regional Pref Ntwk EPO POS + PPO',
        'Amerihealth Regional Preferred Network HMO, HMO+, POS, POS+ MRF',
        'Emblem Health Select Care Bronze',
        'Amerihealth Local Value Network EPO POS + PPO',
        'Amerihealth Local Value Network HMO HMO + POS',
        'Oxford Health Garden State',
        'Amerihealth Local Value Network - EPO - PPO MRF',
        'Empire Blue Priority EPO',
        'Connecticare Flex Connecticut',
        'Horizon BCBS OMNIA - TIER1',
        'Anthem PPO Century Preferred CT',
        'Anthem CT HMO BlueCare',
        'Medicare',
        'MVP HMO',
        'MVP Premier Plus HMO Small Groups',
        'MVP Health Plan Premier HMO - Individuals',
        'MVP Secure - NY',
        'Multiplan PHCS',
        'Aetna',
        'AgeWell New York',
        'Horizon BCBS OMNIA - TIER2',
        'Metroplus',
        'Cigna',
        'Aetna Select',
        'Oxford',
        'CDPHP HMO',
        'CDPHP New York State of Health - Individuals & Families',
        'United Healthcare',
        'MagnaCare',
        'Multiplan',
        'Connecticare',
        'Harvard Pilgrim PPO',
        'CIGNA LocalPlus',
        'Blue Cross Blue Shield',
        'GHI',
        'Harvard Pilgrim HMO',
        'Coventry HealthAmerica PPO',
        'Harvard Pilgrim ChoiceNet HMO',
        'HealthFirst',
        'Fidelis Care',
        'Amida Care',
        'Humana National POS',
        'Railroad Medicare',
        'HIP',
        'Connecticare Passage',
        'Humana',
        'Tricare',
        'IBC Keystone HMO POS',
        'IBC Personal Choice PPO',
        'Highmark Comprehensive Care Blue PPO 1500 MRF',
        'Highmark Shared Cost Blue PPO 6000 MRF',
        'Anthem CT Pathway X Enhanced Ind HMO',
        'Highmark Alliance Flex Blue',
        'Highmark Blue Cross Blue Shield Shared Cost 1500, a Multi-State Plan',
        'Highmark Community Blue Flex EPO',
        'Highmark Comprehensive Care Flex Blue PPO 500 MRF',
        'Highmark Health Savings Blue PPO 1400 MRF',
        'Anthem Pathway X Ind PPO Direct Access CT',
        'Coventry HealthAmerica HMO',
        'BCBS IL PPO',
        'UnitedHealthcare',
        'Aetna CT AWH MC OA w/Pediatric Dental',
        'Connecticare Choice',
        'Humana Preferred PPO',
        'Highmark PPOBlue',
        'HealthyCT',
        'Capital BC PPO',
        'Delta Dental Premier',
        'Delta Dental PPO',
        'Tufts PPO',
        'Geisinger Health Plan',
        'CIGNA Total DPPO',
        'Coventry DE PPO',
        'Most Insurance Plans Accepted',
        'Principal Dental PPO',
        'MetLife PDP',
        'Guardian DentalGuard Preferred',
        'Assurant DHA Premier',
        'UHC Optimum Choice Preferred POS',
        'Ameritas PPO',
        'Assurant DHA',
        'CIGNA Radius Network',
        'Dental Network of America DPPO',
        'Aetna DPPO',
        'Empire Blue Cross Blue Shield',
        'BCBS MA HMO Blue with Managed Care Behavioral Health',
        'Humana HMO',
        'Humana HMO Premier',
        'United Healthcare Dental PPO',
        'CareFirst BlueChoice Advantage',
        'Anthem Blue Access PPO',
        'Cigna',
        'Tufts Granite Advantage EPO, PPO and Saver',
        'CareFirst BluePreferred PPO',
        'Excellus BCBS Base Bronze Silver Gold Platinum Plans',
        'Florida Blue BlueOptions',
        'Coventry Southern Health PPO',
        'Excellus BluePPO',
        'Oxford Health Plans',
        'Florida Blue BlueCare HMO',
        'Emblem',
        'Wellcare',
        'Blue Cross CA  PPO Prudent Buyer Small Group',
        'Geisinger Mrktplace Plans',
        'Affinity',
        'Health Net CA PPO',
        'Anthem KeyCare PPO',
        'Blue Cross CA PPO Prudent Buyer Individual',
        'Health Net CA HMO Employer Group',
        'United Concordia Advantage Plus PPO',
        'United Concordia Alliance',
        'Anthem Blue Preferred HMO',
        'Blue Cross CA PPO Prudent Buyer Large Group',
        'BCCA Dental Blue 100/200/300',
        'Blue Cross CA Advantage PPO Preferred DirectAccess Plus',
        'Excellus HMOBlue',
        'Neighborhood Health Partnership Commercial',
        'DenteMax Dental',
        'CareFirst Maryland POS',
        'Humana Dental PPO',
        'PHCS PPO Kaiser',
        'Blue Shield CA Bronze Full PPO 4500',
        'United Concordia National Fee-For-Service',
        'Anthem HealthKeepers HMO POS',
        'BCBS TX BlueChoice',
        'Coventry FL Employer Group PPO',
        'Blue Cross CA Select Plus HMO',
        'Capital BC Keystone Health Plan Central HMO',
        'CompBenefits PPO',
        'EmblemHealth Medicare',
        'Health Net CA Individual and Family PPO',
        'Humana HMO Select',
        'Blue Shield CA PPO',
        'UHC Medica Choice',
        'Blue Cross CA Select PPO',
        'AvMed Empower',
        'UHC West SignatureValue HMO',
        'Avmed Choice',
        'Blue Cross CA California Care Large Group HMO',
        'Dominion Dental PPO',
        'Emblem Dental - Preferred Plus',
        'Harvard Pilgrim ElevateHealth HMO',
        'Blue Shield CA Access Plus HMO',
        'BCBS MA HMO Blue Select',
        'Blue Cross CA Pathway X PPO',
        'HealthLink PPO',
        'Humana National HMO',
        'Coventry FL Employer Group HMO Open Access',
        'BC CA California Care Small Group HMO',
        'BCBS Florida myBlue',
        'Blue Shield CA Bronze 60 PPO SHOP',
        'Aetna HMO Deductible Plan CA only',
        'BS CA Platinum 90 PPO',
        'Anthem BC Pathway X EPO Network',
        'Blue Shield CA Silver 70 PPO',
        'Blue Shield CA Platinum Access+ HMO 25',
        'Health Net CA HMO Whole Care Network',
        'Coventry MO PPO',
        'Florida Blue BlueSelect ',
        'Health Net PureCare One EPO Individual & Family Plan',
        'Blue Cross CA Select HMO',
        'Ambetter Superior Health Plan',
        'Medicare',
        'UPMC PPO',
        'CIGNA Dental DHMO',
        'Anthem Pathway X Tiered Hospital and Dental Prime MRF',
        'Coventry MO HMO POS',
        'EmblemHealth',
        'Sagamore Plus',
        'Aetna DMO',
        'BCBS MI PPO Plans Group Enrollees',
        'Anthem Pathway X Tier Hosp HealthKeepers DirectAccess VA',
        'Aetna PPO',
        'Health Net PureCare HSP Individual and Family Plans',
        'Highmark KeystoneBlue',
        'Horizon Dental PPO',
        'Aetna Health Network Option Open Access',
        'BCBS NC BlueOptions',
        'Anthem PPO',
        'Blue Shield CA Local Access Plus HMO',
        'Aetna Basic HMO',
        'Blue Shield CA Access Plus Savenet',
        'Coventry Health and Life IL PPO',
        'HealthNow - NYSOH Mrktplace',
        'PriorityHealth Priority PPO',
        'UHC West SignatureValue Advantage HMO Value Network',
        'Ambetter from CelticCare Health MRF',
        'Cash/Self pay',
        'UHC West SignatureValue Alliance',
        'Blue Shield CA Platinum Local Access + HMO 25',
        'Anthem Blue Open Access POS Alternate Network',
        'BCBS GA Blue Choice PPO',
        'BCBS NC Blue Select',
        'Coventry IL PPO',
        'Delta Dental DeltaCare USA',
        'UPMC Premium Network Plans',
        'Coventry PPO Platinum',
        'Kaiser Permanente',
        'BCBS GA Blue Open Access POS ',
        'BCBS TX Blue Advantage HMO',
        'Empire BCBS',
        'AvMed Engage',
        'BCBS IL BlueChoice Select',
        'Medmutual OhioHealth Network MRF',
        'BCBS NC Blue Value',
        'Independent Health Encompass HMO',
        'Moda Health First Choice Network',
        'PHCS',
        'Aetna Savings Plus of CA',
        'Coventry Carelink - Carolinas HealthCare System Tier 2',
        'Humana South Florida HUMx HMOx',
        'Independent Health FlexFit HMO',
        'Ambetter Sunshine Balanced MRF',
        'Horizon Blue Cross Blue Shield of New Jersey',
        'Humana HMO Premier MRF',
        'MMOH SuperMed POS Select',
        'MMOH SuperMed PPO Plus',
        'WPS Group',
        'Aetna Vitalidad Plus CA con Aetna',
        'Anthem Preferred Blue Network - NH',
        'BCBS GA Blue Choice HMO',
        'BCBS GA BlueChoice Option POS',
        'Blue Cross CA Pathway X HMO',
        'Health Alliance PPO',
        'Health Net CA CommunityCare Network HMO',
        'Minuteman Health Massachusetts',
        'CHN PPO',
        'HAP Preferred PPO',
        'Molina Mrktplace - TX MRF',
        'Preferred One PPO',
        'Anthem Blue Preferred Plus POS',
        'Medicaid',
        'Molina Mrktplace CA',
        'QualCare',
        'SIHO Network',
        'Self Pay',
        'UHC SignatureValue Focus',
        'Anthem Blue Cross',
        'Guardian Managed DentalGuard',
        'UHC SignatureValue Flex1',
        'Anthem CO HMO',
        'BCBS AZ Neighborhood Network MRF',
        'Blue Cross CA Priority Select HMO',
        'CareFirst BlueChoice HMO',
        'Common Ground Empower Trilogy',
        'Coventry CoventryOne - GA',
        'Horizon BCBS',
        'Horizon NJ TotalCare',
        'Optima Health OptimaFit Direct HMO',
        'Optima Vantage HMO',
        'Anthem BCBS',
        'Anthem CO Blue Priority PPO',
        'Anthem MO Blue Preferred Options',
        'BCBS RI HealthMate Coast to Coast',
        'Blue Shield CA Trio ACO HMO',
        'Cigna MISSOURI NET - NET POS Seamless',
        'Coventry FL Carelink HMO',
        'Health Net CA HMO SmartCare',
        'Premera LifeWise Connect',
        'Aetna Choice POS',
        'Aetna Health Network',
        'BCBS MN Blue Cross Accord',
        'BCBS South Carolina',
        'Coventry KS PPO',
        'GEHA',
        'UHC SignatureValue Flex3',
        'BCBS MI Blue Care Network HMO Group Enrollees',
        'HAP HMO Full Network',
        'HealthSpan Access PPO',
        'New York State Employee Helth Insurance Plan (Empire Plan)',
        'PriorityHealth HMO',
        'UHC SignatureValue Flex2',
        'UPMC Partner Network Plans',
        'Workers Compensation',
        'Aetna VA Signature Gold HMO',
        'Anthem Pathway X - KY',
        'BCBS GA Pathway X Enhanced POS',
        'BCBS GA Pathway X Ind Direct Access',
        'Blue Shield CA 2017 I&F HMO - CoveredCA',
        'Coventry OA EPO Exchange - KS/MO',
        'Empire Blue Cross Blue Shield Health Plus',
        'Guardian PPO',
        'Molina Mrktplace OH MRF',
        'Alliant Health Plan',
        'Anthem CO Bronze Pathway X HMO',
        'Anthem Pathway X HMO',
        'BCBS SC BlueEssentials Network',
        'Blue Cross/Blue Shield PPO',
        'Oscar Insurance CA',
        'Premera Heritage and Heritage Plus 1',
        'Regence WA Preferred Provider Network',
        'Aetna Innovation Health Leap',
        'Anthem CO Gold Pathway HMO',
        'Anthem CO Pathway',
        'Harvard Pilgrim Maines Choice HMO',
        'Health Alliance HMO/POS',
        'PacificSource PSN',
        'Premera Heritage Signature',
        'UPMC I&F - Select Network',
        'Aetna Delaware PPO',
        'Anthem Blue Choice PPO - ME',
        'Anthem CO Silver Pathway X HMO',
        'Anthem MO Pathway X',
        'Anthem',
        'BCBS LA HMO LA HMO/POS MRF',
        'Blue Cross',
        'HealthPartners Open Access',
        'United Healthcare Medicare Advantage',
        'Anthem Blue Cross Blue Shield',
        'Anthem HMO Maine',
        'Anthem IN Pathway X Bronze Direct CACA HIX',
        'BCBS AL PPO',
        'Blue Cross ID PPO',
        'Cigna POS',
        'Coventry Virginia - HMO',
        'Moda Health Connexus',
        'Aetna Savings Plus of AZ',
        'Altius Provider Directory',
        'Amerigroup',
        'Anthem MO Direct Access w/HSA',
        'Anthem Pathway - ME',
        'Anthem Pathway X - ME',
        'Anthem Pathway X Enhanced Ind Direct Access NH',
        'BCBS OK BlueChoice',
        'Community Health Choice Mrktplace MRF',
        'Coventry - Southside Tier 2',
        'HealthPartners MN CentraChoice',
        'HealthPartners MN Distinctions II',
        'Humana Tampa Bay CoreNet',
        'Tufts Granite Premier Choice EPO and PPO',
        'Aetna Delaware Health Network Only Open Access',
        'Aetna Medicare',
        'BCBS AZ Alliance Network',
        'BCBS TN Blue Network S',
        'FirstCare PPO',
        'FirstCare Select',
        'HealthCare Partners',
        'HealthPartners MN CareChoices',
        'PHP Select with Encircle',
        'PPO-CIGNA',
        'Qualchoice Statewide Network',
        'Rocky Mountain Good Health and Vista HMO PPO',
        'Rocky Mountain Monument PPO - Tier 2',
        'Rocky Mountain Summit Group',
        'Workmans Comp',
        'Ambetter from Superior HealthPlan MRF',
        'Anthem Pathway X Tiered PPO',
        'BCBS LA Preferred Care PPO',
        'Blue Cross CA Vivity',
        'CIGNA Southern CA Value',
        'Coventry - Bon Secours Tier 2',
        'Coventry IA PPO',
        'Empire Blue Cross Blue Shield (Wellpoint) PPO',
        'Encore Health Network',
        'Harvard Pilgrim New Hampshire Network HMO',
        'Horizon',
        'Molina Mrktplace - NM MRF',
        'Providence PPO',
        'Scott and White PPO',
        'Unicare',
        'UnitedHealthcare Community Plan',
        'UnitedHealthcarePPO',
        'Univera Healthcare Preferred Gold - Tier 1 & 2',
        'Aetna Better Health (ABD)',
        'Ambetter - CCCWA Exchange MRF',
        'BCBS IL Blue Advantage HMO',
        'BCBS IL HMO Illinois',
        'Blue Cross/Blue Shield HMO',
        'CareSource Just4Me OH',
        'EmblemHealthPPO',
        'Excellus BCBS Bassett Preferred Gold/Silver - Tier 1',
        'Excellus BCBS CNY Preferred Gold - Tier 1 & 2',
        'Health Net AZ PPO HSA',
        'Independence Blue Cross',
        'LACare',
        'Moda Health Synergy Network',
        'Molina Mrktplace FL',
        'Regence OR Preferred Provider Network',
        'UHC',
        'Aetna Coastal VA Managed Choice Open Access',
        'Aetna Medicare Advantage',
        'Ambetter From NH Health Families MRF',
        'Anthem Pathway Enhanced - ME',
        'Anthem Pathway X Enhanced/Ind Guided Access ME',
        'BCBS KC Preferred Care Blue PPO',
        'BCBS PPO',
        'CareSource Just4Me KY',
        'Colorado Choice Health Plans',
        'Health Net OR PPO',
        'Maine Community Health Options',
        'MetLife HMO',
        'PPO-MULTIPLAN',
        'Wellmark Alliance Select',
        'Aetna POS',
        'Aetna Whole Health Colorado Front Range',
        'Amerihealth',
        'BCBS IL Blue Precision HMO',
        'BCBS LA BlueConnect HMO POS',
        'BCBS LA Community Blue HMO POS',
        'BCBS MT Blue Preferred PPO',
        'BCBS NC Blue Local',
        'BCBS TX HMO Blue Texas',
        'Baptist Health Community Care Network',
        'CareCredit',
        'CommunityCare PPO Standard Network',
        'Coventry NE PPO',
        'Coventry',
        'Empire Blue Cross Blue Shield (Wellpoint) EPO',
        'HMSA Preferred Provider Comp Med',
        'Health Alliance IL IA Public Mrktplace QHP Provider Directory',
        'Humana Tampa Bay HUMx HMOx',
        'MDWise Mrktplace',
        'Medicaid NY',
        'Medicaid',
        'NYS EMPIRE',
        'Network Health Plan HMO POS',
        'OptumHealth',
        'PacificSource SmartChoice',
        'PacificSource SmartHealth Oregon Members',
        'Pomco',
        'Regence Preferred FocalPoint',
        '1199SEIU',
        'Aetna EPO ',
        'Aetna Whole Health Arizona Care Network',
        'Ambetter Illinicare Health Network MRF',
        'Anthem CO  Blue Priority HMO',
        'BCBS NM PPO NM',
        'BCBS WY BlueSelect MRF',
        'Beech Street',
        'Blue Cross/Blue Shield POS',
        'Cigna Southern CA Select',
        'Common Ground Health COOP Envision Aurora',
        'Community Care PCC',
        'EmblemHealthEPO',
        'Empire Blue Cross Blue Shield (Wellpoint) HMO',
        'Empire Blue Priority EPO',
        'Group Health Coop Alliant Plus Connect',
        'Guardian Managed Dental Care',
        'Health Net SmartCare Large Group',
        'HealthNet',
        'Humana Colorado HMOx',
        'MEDICARE SELF PAY/CASH',
        'PPO-AETNA (STANDARD NETWORK)',
        'PPO-BLUE SHIELD (STANDARD NETWORK)',
        'SummaCare Select Fully Insured',
        'Ambetter from Peach State Health Plan',
        'Anthem NV Choice PPO',
        'BCBS MN BluePrint',
        'BCBS TN Blue Network E',
        'Blue Cross/Blue Shield Medicare Advantage',
        'Cigna Connect Network - MO',
        'Coventry Carelink - Duke Medicine Tier 1',
        'Coventry PPO - TN',
        'CoventryOne PPO Network',
        'EmblemHealthPOS',
        'Fidelis',
        'First Health',
        'FrontPath Health Coalition',
        'Group Health Coop Core',
        'HAP Personal Alliance HMO - Henry Ford Choice',
        'Humana Houston HMOx',
        'MMOH Mercy Health - HMO',
        'Medicaid NY Emblem Health (Formerly known as HIP)',
        'MetLife',
        'Moda Health Community Care Network',
        'Network Health Plan Individual',
        'Oscar - San Antonio MRF',
        'PacificSource SmartHealth Standard MRF',
        'Pacificsource SmartChoice OR MRF',
        'SIHO Mrktplace Network',
        'Tricare PPO',
        'Western Health Advantage',
        '1199',
        'Aetna Coventry FirstHealth',
        'Aetna US Healthcare',
        'Aetna Whole Health Banner Health Network HMO',
        'Ambetter from MHS HIX',
        'Anthem HMO Nevada',
        'Anthem NV Pathway PPO',
        'Anthem NV Pathway X HMO Ind Direct Access',
        'BCBS',
        'Blue Cross/Blue Shield HMO Medicaid',
        'Blue Cross/Blue Shield Medicaid',
        'Buckeye Ambetter Balanced',
        'CareSource Just4Me IN',
        'Cigna Connect Network - IL',
        'Cigna Connect Network EPO',
        'Coventry - Southside Tier 1',
        'Coventry Carelink - Carolinas HealthCare System Tier 1',
        'Delta Dental',
        'Empire Blue Cross Blue Shield (Wellpoint) POS',
        'Empire Plan - NYSHIP',
        'First Managed Care Option Workers\' Compensation (FMCO WC)',
        'Guardian',
        'HMO-CIGNA',
        'Health Net CA Primary EPO',
        'Health Net SmartCare Small Group',
        'Horizon BCBS OMNIA - TIER1',
        'Horizon Casualty',
        'Humana Illinois HMOx MRF',
        'Humana Louisiana HMOx MRF',
        'Humana Volusia HUMx HMOx',
        'IU Health EMPLOYER PLAN',
        'InterGroup',
        'Medica with Mayo Clinic',
        'Medicaid NY Empire Blue Cross Blue Shield HealthPlus (Formerly knows as Amerigroup)',
        'MetroPlus Health Plan',
        'Minuteman Health NH Individual',
        'Moda Health Beacon',
        'Motor Vehicle (NJ)',
        'No-Fault Insurance',
        'Oscar',
        'OxfordMetro Plan',
        'POS-AETNA (STANDARD NETWORK)',
        'POS-CIGNA',
        'PacificSource SCN MRF',
        'Paradigm Specialty Networks',
        'Procura (NJM)',
        'Promesa',
        'SELF PAY/CASH WORKERS COMPENSATION',
        'Scion Dental',
        'Sendero IdealCare',
        'Sharp Health Blue Choice',
        'Three Rivers Provider Network (TRPN)',
        'Unicare PPO',
        'Workers\' Compensation',
        'Aetna Dental Access',
        'Aetna QHP',
        'Aetna Whole Health/Attribution',
        'Aetna Whole Health',
        'AmeriHealth HMO, POS, DPOS',
        'Aultcare PPO',
        'BCBS Blue Advantage PPO',
        'BCBS IL BlueCare Direct',
        'BCBS LA Blue Cross Dental Network',
        'BCBS MN BlueConnect',
        'Blue Shield',
        'Cigna (CAC)',
        'Cigna Behavioral Health',
        'Cigna Behavioral',
        'Cigna TN EPO Nashville and Tri-Cities',
        'Cigna Tennessee Memphis LP-EPO Network MRF',
        'Coresource',
        'Coventry MT Health Co-op Access Care',
        'EPO-CIGNA',
        'Empire BCBS HMO',
        'Great-West Life PPO',
        'Health Net OR CommunityCare',
        'Health Net Salud EPO',
        'Health Plan of Upper Ohio PPO',
        'Healthplex Dental Amerigroup NJ Medicaid',
        'Hometown Health Commercial PPO',
        'Hometown Health Premier HMO',
        'Humana Health Plan',
        'Humana Lexington UK HealthCare HMOx',
        'Humana Norton + Just For Kids HMOx',
        'Humana Phoenix HMOx',
        'Imagine Health SmartCare',
        'Medicare Non-par',
        'Meritain',
        'Moda Health Summit',
        'Molina Mrktplace WI',
        'NM Health Connections Harvest Choice Connect HMO',
        'One Health Network',
        'Pacificsource PSN/Balance MRF',
        'Piedmont Individual Mrktplace HMO',
        'Piedmont Individual Mrktplace PPO',
        'Premera MultiCare Connected Care',
        'Premera',
        'Presbyterian ASO',
        'Presbyterian Commercial',
        'Principal',
        'Regence Evergreen Health Partners',
        'Regence ID Preferred Provider Network',
        'SELF PAY/CASH PPO-AETNA (STANDARD NETWORK)',
        'Security Health Plan Classic',
        'Sharp Health Gold Value',
        'Unicare HMO',
        'UnitedHealthcarePOS',
        'Unity Health Ins Unity Network',
        'VSP Choice Access',
        'Value Options',
        'AARP',
        'Aetna Choice POS II on the Altius Network',
        'Aetna Crisis Response Center',
        'Aetna VA Whole Health MC OA',
        'Aetna Whole Health PrimeCare HMO CA',
        'Amerihealth Local Value Network',
        'Ameritas',
        'Anthem BCBS of Connecticut',
        'Anthem Pathway X PPO',
        'BC ID ConnectedCare-Saint Alphonsus Health Alliance-Southwest',
        'BCBS AL Preferred Dentists',
        'BCBS Blue Alliance (BHN Acclaim)',
        'BCBS TX BlueCare Dental',
        'Blue Cross Blue Shield of Western New York',
        'Blue Cross CA PPO Prudent Buyer Small Group',
        'Blue Cross Gold',
        'Blue Cross Silver',
        'Blue Cross and Blue Shield Crisis Response Center',
        'Blue Cross of Idaho',
        'Blue Cross/Blue Shield-MCNP PPO',
        'Blue Shield of CA',
        'Blue Shield of California',
        'BlueCard PPO Basic',
        'BlueCard PPO/EPO',
        'BlueCard Traditional',
        'CCN PPO',
        'Care1st',
        'CareFirst Regional Preferred Dental PPO',
        'Careington POS',
        'Child Health Plan Plus',
        'ChoiceCare/Network (Humana)',
        'Choice',
        'Christus Exchange NM',
        'Christus Exchange TX',
        'Cigna Health Spring - HMO Medicare',
        'Cofinity PPO',
        'CorVel WC',
        'Coventry - Bon Secours Tier 1',
        'Davis Vision',
        'Dean Health Systems place healthcaregov HMO',
        'EMPLOYEES HOSPITAL ASSOC (GEHA)',
        'EmblemHealth Prime',
        'GHI / Emblem Health',
        'HMO-UNITED HEALTH CARE (STANDARD NETWORK)',
        'HMO-UNITED HEALTH CARE MEDICARE (FORMERLY KNOWN AS SECURE HORIZONS)',
        'Health Net EPO - PureCare One Small Business',
        'Highmark Blue Cross Blue Shield',
        'Humana (Commercial Only)',
        'Humana Atlanta HMOx',
        'Humana Dayton HMOx',
        'Humana Knoxville PPOx',
        'Humana Medicare Advantage',
        'Humana Nashville PPOx',
        'Humana PPO',
        'Humana SW Missouri PPOx',
        'Kaiser Permanente MidAtlantic',
        'Liberty Dental CA Independence PPO',
        'Lincoln Financial',
        'Medica Fairview and N Memorial Vantage',
        'Medicare CA',
        'Medicare Shared Savings Program',
        'Meritain Health',
        'Multiplan/Beech Street/PHCS',
        'Optima Health OptimaFit Select HMO',
        'Out-of-Network',
        'POS-ANTHEM BLUE CROSS (STANDARD NETWORK)',
        'PPO-BEECH STREET(FORMERLY CAPP CARE)',
        'PPO-GOVERNMENT EMPLOYEES HOSPITAL ASSOC (GEHA)',
        'PPO-GOVERNMENT',
        'PPO-HUMANA',
        'PPO-UNITED HEALTH CARE (STANDARD NETWORK)',
        'PacificSource SHN CAT MRF',
        'PacificSource SHN MRF',
        'Paramount HMO Ohio',
        'Paramount Ins Co Individual place',
        'Preferred Network Access by CIGNA',
        'Premera VA Mason Med Center: Personal Care',
        'Prominence N NV - HealthFirst HMO/POS Network Employer',
        'Prominence N Nevada - Preferred Healthcare PPO Employer',
        'Providence Choice Network',
        'QualCarePOS',
        'Regence MyChoice NW',
        'SelectHealth Select Value',
        'Select',
        'Sharp Health Performance',
        'Sharp Health Premier',
        'Sierra Health Northern Nevada PPO',
        'Sun Life Financial',
        'UMR',
        'United Concordia',
        'United HealthCare Select Plus',
        'UnitedHealthcare PPO Plans',
        'UnitedHealthcareHMO',
        'VSP',
        'DP CompleteCare',
        'ACPN',
        'ADI Ultra Care Plan',
        'Advantage PPO',
        'Aetna Commercial',
        'Aetna Signature Administrators (PPO)',
        'Aetna Value Network HMO NV Only',
        'Aetna Vital Dental Savingsâ„ ',
        'Aetna Whole Health Pacific Medical Centers WA',
        'Aetna Whole Health PrimeCare OAMC CA',
        'Aetna Whole Health Providence Swedish WA',
        'Aexcel Choice POS II (Aetna HealthFund)',
        'Aexcel Choice POS II',
        'Aexcel Managed Choice POS (Open Access)',
        'Aexcel Managed Choice POS',
        'Aexcel Open Access Managed Choice POS (HealthFund)',
        'Aexcel PPO (Aetna HealthFund)',
        'Aexcel PPO',
        'Aexcel Plus Choice POS II (Aetna HealthFund)',
        'Aexcel Plus Choice POS II',
        'Aexcel Plus Managed Choice POS (Open Access)',
        'Aexcel Plus Managed Choice POS',
        'Aexcel Plus Open Access Managed Choice POS (HealthFund)',
        'Aexcel Plus PPO (Aetna HealthFund)',
        'Aexcel Plus PPO',
        'Anthem Blue Cross GenRx',
        'Anthem Blue Cross Life and Health Insurance Company',
        'Anthem Blue Cross OnePlan PPO',
        'Anthem Blue Cross POS',
        'Anthem Blue Cross Premier PPO',
        'Anthem CT',
        'Anthem Gold PPO',
        'Anthem Gold Select PPO',
        'Anthem Medicare Preferred (PPO)',
        'Anthem Medicare Preferred Standard (PPO)',
        'Anthem Pathway X Tiered Hospital',
        'Anthem Platinum PPO',
        'Anthem Platinum Select',
        'Anthem Silver PPO',
        'Anthem Silver Select PPO',
        'Anthem WI Blue Priority X Indiv DirectAccess',
        'Aon Dental Solutions Plan',
        'Arizona Foundation Crisis Response Center',
        'Arizona Foundation',
        'Arizona Medical Network/PHCS/Beech Street',
        'Arizona Physicians IPA',
        'Assurant',
        'Asuris',
        'Aultcare ExchangeProviders',
        'Aultcare HMO',
        'Auto Insurance',
        'Avia Dental Plan',
        'BC ID ConnectedCare-Portneuf Quality Alliance-East',
        'BCBS Blue Alliance (BHN Acclaim) Crisis Response C',
        'BCBS GA Dental Complete',
        'BCBS TX DentaBlue',
        'BCBS of NE',
        'BCBS of WY',
        'BSCA Dental PPO',
        'Beacon',
        'Beech Street/Capp Care PPO',
        'Beech Street',
        'Best Life',
        'Blue AZ Advantage Crisis Response Center',
        'Blue AZ Advantage',
        'Blue Access PPO',
        'Blue Choice Crisis Response Center',
        'Blue Cross Blue Shield of Arizona',
        'Blue Cross Blue Shield of Arkansas',
        'Blue Cross Blue Shield of Georgia',
        'Blue Cross Blue Shield of Illinois',
        'Blue Cross Blue Shield of Louisiana',
        'Blue Cross Blue Shield of Michigan',
        'Blue Cross Blue Shield of South Carolina',
        'Blue Cross Bronze',
        'Blue Cross and Blue Shield AZ',
        'Blue Cross and Blue Shield of Florida FamilyBlue Discount Plan',
        'Blue Cross and Blue Shield of Florida, Inc. d/b/a Florida Blue',
        'Blue Cross/Blue Shield-Workers Choice WC',
        'Blue Medicare Advantage',
        'Blue Shield of Northeastern New York',
        'Bonus Benefits',
        'Bridgeway Crisis Response Center',
        'Bridgeway Health Solutions',
        'CHOICE CARE NETWORK',
        'CIGNAPlus Savings Powered By CIGNA Dental Network Access',
        'COMMERCIAL/INDEMNITY MEDICARE ASSIGNMENT',
        'CareFirst Regional Traditional Dental',
        'Careington Care 500 Series',
        'Careington Platinum POS Plan',
        'Center Care',
        'Charter HMO / Charter Balanced HMO / Charter Plus HMO',
        'Charter Plus',
        'Chinese Community Health Plan',
        'Choice Fund Open Access Plus with CareLink',
        'Choice Fund Open Access Plus',
        'Choice Fund PPO',
        'Choice HMO',
        'Cigna 1000 Dental Insurance',
        'Cigna 1500 Dental Insurance',
        'Cigna Behavioral Health Crisis Response Center',
        'Cigna Connect 100',
        'Cigna Connect Flex Gold',
        'Cigna Connect Flex Silver',
        'Cigna Connect Gold',
        'Cigna Connect HSA Silver',
        'Cigna Connect Silver',
        'Cigna FocusIn Flex Gold',
        'Cigna FocusIn Flex Silver',
        'Cigna FocusIn HSA Silver',
        'Cigna Health Savings',
        'Cigna Healthcare AZ',
        'Cigna Non-CAC',
        'Cigna Open Access',
        'Cigna Vantage Gold',
        'Cigna and Great West',
        'Cigna/Great West',
        'Clarksville Medical Network',
        'Clover Health (Medicare plan)',
        'Clover Health',
        'Cofinity',
        'Commonwealth of VA',
        'Community Health Group',
        'CompBenefits AdvantagePlus Plans',
        'Coventry Health Care of Nevada PPO',
        'Coventry Healthcare',
        'Coventry Peak Advantage - UT',
        'Delta Dental of Illinois',
        'DentalSave Discount Dental Plan',
        'Dentegra',
        'Devoted Health Plan',
        'Doctors Plan HMO / Doctors Plan Plus HMO',
        'Doctors Plan Plus',
        'Doctors Plan',
        'Dominion National',
        'EBCBS HMO',
        'EBCBS Mediblue',
        'EBCBS NYPH Employees Only',
        'EBCBS PPO/EPO',
        'EPO-AETNA (STANDARD NETWORK)',
        'EPO-ANTHEM BLUE CROSS (STANDARD NETWORK)',
        'EPO-BLUE SHIELD (STANDARD NETWORK)',
        'Emblem HIP',
        'EmblemHealthHMO',
        'Empire BCBS XCHG',
        'EmployerDirect Healthcare',
        'FL Blue BlueDental Choice & Choice Plus PPO',
        'First Choice of the Midwest',
        'First Dental Health',
        'FirstHealth/Coventry',
        'Great-West Life HMO',
        'Great-West',
        'Gundersen Health Plan Select Network',
        'HFN Inc. PPO',
        'HIP Commercial',
        'HMO-AETNA (STANDARD NETWORK)',
        'HMO-ANTHEM BLUE CROSS (STANDARD NETWORK)',
        'HMO-INDUSTRY HEALTH NETWORK',
        'HMO',
        'Harvard',
        'Health Choice of Arizona',
        'Health Choice',
        'Health Infonet',
        'Health Management Network',
        'Health Management',
        'Health Net Ambetter/CommunityCare HMO',
        'Health Net SmartCare Large Group',
        'Health Net',
        'Health Plan of NV HMO My HPN MIPLAN BIEN Northern NV Plan HMO',
        'Health Plan of NV HMO Northern NV',
        'Health Plan of NV HMO Rural NV',
        'Health Republic Insurance of New Jersey',
        'HealthPlus Amerigroup',
        'HealthSmart',
        'Healthsmart Accel',
        'Healthsmart HPO',
        'Horizon BCBS OMNIA - TIER2',
        'Horizon Health Care',
        'Humana  Tricare (Medicare plan)',
        'Humana Benefit Plan of Illinois',
        'Humana ChoiceCare PPO',
        'Humana Cincinnati/Northern KY HMOx',
        'Humana Employers Health Plan of Georgia',
        'Humana Gold Plus',
        'Humana Health Benefit Plan of Louisiana',
        'Humana Health Plan of Ohio',
        'Humana Health Plan of Texas',
        'Humana Memphis PPOx',
        'Humana Nashville PPOx MRF',
        'Humana North Carolina PPOx',
        'Humana POS',
        'Humana Rio Grande EPOx',
        'Humana Savannah HMOx',
        'Humana Veterans',
        'Humana/CompBenefits',
        'HumanaOne',
        'Individual KeyCare Preferred',
        'KeyCare Flexible Choice',
        'KeyCare Healthsmart',
        'Liberty Dental Program of America',
        'Local 164 Electrical Union',
        'MediBlue',
        'Medica Inspiration HealthEast',
        'Medica North Memorial Acclaim',
        'Medicaid HMO',
        'Medicare Advantage HMO',
        'Medicare Advantage Plans',
        'Medicare CO',
        'Medicare Crisis Response Center',
        'Medicare HMO',
        'Medicare NE',
        'Medicare NV',
        'Medicare Sierra Vista',
        'Medicare WY',
        'Meridian (Medicaid)',
        'Molina',
        'National Association of Letter Carriers (NALC)',
        'National Benefit Fund For Home Care Employees',
        'National Vision Administrators (NVA)',
        'Network Open Access',
        'Ohio, Anthem Blue Cross and Blue Shield',
        'One Call Medical',
        'OneNet PPO',
        'Open Access Plan',
        'Open Access Plus/CareLink',
        'Open Access Plus',
        'Open Access Value Plan',
        'Open Access Value',
        'Open Access',
        'PHCS EPO',
        'PHCS POS',
        'POS-HEALTH NET (STANDARD NETWORK)',
        'PPO-FIRST HEALTH (COVENTRY)',
        'PPO-HUMANA CHOICE CARE NETWORK',
        'PPO-PPO NEXT',
        'PPO-PRIVATE HEALTHCARE SYSTEMS (PHCS)',
        'PPO',
        'Passport Connect Choice Plus',
        'Preferred Network Access by CIGNA (Dental Only)',
        'Premera NW PHYS Network: Personal Care',
        'Prominence N NV - Premier HMO Employer',
        'Prominence Southern Nevada - HMO Employer Sponsored',
        'Providence Health System Connect Network',
        'Providence Medical Network IPA',
        'Regence UW Medicine',
        'Renaissance Dental Insurance Plan III',
        'Sele-Dent Discount Dental Plan',
        'Select HMO',
        'Select Health Select Med',
        'Spectera',
        'Standard',
        'Superior Vision',
        'The New York Cornell IPA',
        'TriWest',
        'UHC Choice Bronze',
        'UHC Choice Gold',
        'UHC Choice Plus Bronze',
        'UHC Choice Plus Gold',
        'UHC Choice Plus Platinum',
        'UHC Choice Plus Silver',
        'UHC Choice Silver',
        'UHC Compass',
        'USA Managed Care',
        'Union Plans',
        'United Commercial ACO',
        'United Concordia DHMO Concordia Plus General Dentist',
        'United Empire Plan',
        'United Health Alliance',
        'United Health Care (UHC - Commercial Plan)',
        'United Healthcare Choice Plus',
        'United Healthcare Choice',
        'United Healthcare Commercial',
        'United Healthcare Dental DHMO CA Only',
        'United Healthcare Select',
        'United Healthcare Workers East',
        'United Healthcare of IL HMO',
        'United Healthcare of IL POS',
        'United Medical Alliance',
        'United Medicare Complete',
        'UnitedHealthcare Benefits of Texas',
        'UnitedHealthcare Choice Plus',
        'UnitedHealthcare Choice with Harvard Pilgrim',
        'UnitedHealthcare Options PPO with Harvard Pilgrim',
        'UnitedHealthcare Options PPO',
        'UnitedHealthcare Oxford',
        'UnitedHealthcare Passport Connect Choice Plus',
        'UnitedHealthcare Passport Connect Choice',
        'UnitedHealthcare Passport Connect Options PPO',
        'UnitedHealthcare Plan of the River Valley',
        'UnitedHealthcare Select Plus POS',
        'UnitedHealthcare Select Plus PPO',
        'UnitedHealthcare of California',
        'VNS Choice',
        'Virginia Advantage',
        'Virginia Basic',
        'Vytra',
        'WORKERS COMPENSATION PPO-AETNA (STANDARD NETWORK)',
        'WORKERS COMPENSATION PPO-ANTHEM BLUE CROSS (STANDARD NETWORK)',
        'Weill Cornell Medicine PPO',
    ];

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        //upload from full list
        foreach ($this->companiesFromDoc as $company) {
            if (!\modules\account\models\ar\InsuranceCompany::find()->andWhere(['name' => $company])->exists()) {
                $model = (new \modules\account\models\ar\InsuranceCompany(['name' => $company]));
                $model->detachBehavior('timestamp');
                $model->detachBehavior('blameable');
                $model->save(false);
            } else {
                \yii\helpers\Console::output('Duplicate entry ' . $company);
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        return true;
    }
}
