<?php

use yii\db\Migration;

/**
 * Class m201109_191117_update_insurance_list
 */
class m201109_191117_update_insurance_list extends Migration
{
    public $companiesFromDoc = [
        "1199",
        "1199SEIU",
        "AARP",
        "Advantage PPO",
        "Aetna Basic HMO",
        "Aetna Better Health (ABD)",
        "Aetna Choice POS",
        "Aetna Choice POS II",
        "Aetna Choice POS II on the Altius Network",
        "Aetna Choice POS Open Access",
        "Aetna Coastal VA Managed Choice Open Access",
        "Aetna Coventry FirstHealth",
        "Aetna CT AWH MC OA w/ Pediatric Dental",
        "Aetna Delaware Health Network Only Open Access",
        "Aetna Delaware PPO",
        "Aetna Dental Access",
        "Aetna DMO",
        "Aetna DPPO",
        "Aetna Elect Choice EPO",
        "Aetna EPO",
        "Aetna Health Network",
        "Aetna Health Network Option Open Access",
        "Aetna HMO",
        "Aetna HMO Deductible Plan CA only",
        "Aetna Innovation Health Leap",
        "Aetna Innovation Health Leap",
        "Aetna Managed Choice POS Open Access",
        "Aetna Medicare Advantage",
        "Aetna NYC Community Plan",
        "Aetna POS",
        "Aetna PPO",
        "Aetna QHP",
        "Aetna Savings Plus of AZ",
        "Aetna Savings Plus of CA",
        "Aetna Select",
        "Aetna Select",
        "Aetna Signature Administrators PPO",
        "Aetna US Healthcare",
        "Aetna VA Signature Gold HMO",
        "Aetna VA Whole Health MC OA",
        "Aetna Vitalidad Plus CA con Aetna",
        "Aetna Whole Health",
        "Aetna Whole Health Arizona Care Network",
        "Aetna Whole Health Banner Health Network HMO",
        "Aetna Whole Health Colorado Front Range",
        "Aetna Whole Health Pacific Centers WA",
        "Aetna Whole Health PrimeCare HMO CA",
        "Aetna Whole Health PrimeCare OAMC CA",
        "Aetna Whole Health Providence Swedish WA",
        "Aetna Whole Health/Attribution",
        "Aexcel Choice POS II",
        "Aexcel Choice POS II (Aetna HealthFund)",
        "Aexcel Managed Choice POS",
        "Aexcel Managed Choice POS (Open Access)",
        "Aexcel Open Access Managed Choice POS (HealthFund)",
        "Aexcel Plus Choice POS II",
        "Aexcel Plus Choice POS II (Aetna HealthFund)",
        "Aexcel Plus Managed Choice POS",
        "Aexcel Plus Managed Choice POS (Open Access)",
        "Aexcel Plus Open Access Managed Choice POS (HealthFund)",
        "Aexcel Plus PPO",
        "Aexcel Plus PPO (Aetna HealthFund)",
        "Aexcel PPO",
        "Aexcel PPO (Aetna HealthFund)",
        "Affinity Essential Qualified Health Plans",
        "AgeWell New York",
        "Alliant Health Plan",
        "Altius Provider Directory",
        "Ambetter - CCCWA Exchange MRF",
        "Ambetter from CelticCare Health MRF",
        "Ambetter from NH Health Families MRF",
        "Ambetter from Superior HealthPlan MRF",
        "Ambetter Superior Health Plan",
        "AmeriHealth HMO, POS, DPOS",
        "AmeriHealth Local Value Network",
        "AmeriHealth Local Value Network - EPO - PPO MRF",
        "AmeriHealth Local Value Network EPO POS + PPO",
        "AmeriHealth Local Value Network HMO HMO + POS",
        "Amerihealth Regional Pref Ntwk EPO POS + PPO",
        "Amerihealth Regional Pref Ntwk HMO HMO + POS",
        "AmeriHealth Regional Preferred Network HMO, HMO+, POS, POS+, MRF",
        "Ameritas PPO",
        "Anthem BC Pathway X EPO Network",
        "Anthem Blue Access PPO",
        "Anthem Blue Choice PPO - ME",
        "Anthem Blue Cross",
        "Anthem Blue Cross OnePlan PPO",
        "Anthem Blue Cross POS",
        "Anthem Blue Cross Premier PPO",
        "Anthem Blue Open Access POS Alternate Network",
        "Anthem Blue Open Access POS Alternate Network",
        "Anthem Blue Preferred HMO",
        "Anthem Blue Preferred HMO",
        "Anthem Blue Preferred Plus POS",
        "Anthem CO Blue Priority HMO",
        "Anthem CO Blue Priority PPO",
        "Anthem CO Blue Priority PPO",
        "Anthem CO Bronze Pathway X HMO",
        "Anthem CO Gold Pathway HMO",
        "Anthem CO HMO",
        "Anthem CO Pathway",
        "Anthem CO Silver Pathway X HMO",
        "Anthem CT HMO BlueCare",
        "Anthem CT Pathway X Enhanced Ind HMO",
        "Anthem Gold PPO",
        "Anthem Gold Select PPO",
        "Anthem HealthKeepers HMO POS",
        "Anthem HMO Maine",
        "Anthem HMO Nevada",
        "Anthem IN Pathway X Bronze Direct CACA HIX",
        "Anthem KeyCare PPO",
        "Anthem KeyCare PPO",
        "Anthem Medicare Preferred (PPO)",
        "Anthem Medicare Preferred Standard (PPO)",
        "Anthem MO Blue Preferred Options",
        "Anthem MO Direct Access w/ HSA",
        "Anthem MO Pathway X",
        "Anthem NV Choice PPO",
        "Anthem NV Pathway PPO",
        "Anthem NV Pathway X HMO Ind Direct Access",
        "Anthem Pathway - ME",
        "Anthem Pathway Enhanced - ME",
        "Anthem Pathway X - KY",
        "Anthem Pathway X - KY",
        "Anthem Pathway X - ME",
        "Anthem Pathway X Enhanced Ind Direct Access NH",
        "Anthem Pathway X Enhanced/Ind Guided Access ME",
        "Anthem Pathway X HMO",
        "Anthem Pathway X Ind PPO Direct Access CT",
        "Anthem Pathway X Ind PPO Direct Access CT",
        "Anthem Pathway X PPO",
        "Anthem Pathway X Tiered Hospital and Dental Prime MRF",
        "Anthem PPO",
        "Anthem PPO",
        "Anthem PPO Century Preferred CT",
        "Anthem PPO Century Preferred CT",
        "Baptist Health Community Care Network",
        "BC CA California Care Small Group HMO",
        "BCBS",
        "BCBS AZ Alliance Network",
        "BCBS AZ Neighborhood Network MRF",
        "BCBS Blue Card PPO",
        "BCBS GA Blue Choice HMO",
        "BCBS GA Blue Choice PPO",
        "BCBS GA Blue Open Access POS",
        "BCBS GA BlueChoice Option POS",
        "BCBS IL PPO",
        "BCBS LA Preferred Care PPO",
        "BCBS MA Blue Care Elect PPO",
        "BCBS MA Preferred Blue PPO",
        "BCBS MN Blue Cross Accord",
        "BCBS MN BluePrint",
        "BCBS NC Blue Local",
        "BCBS NC Blue Select",
        "BCBS NC BlueOptions",
        "BCBS South Carolina",
        "BCBS TN Blue Network S",
        "BCBS TX Blue Advantage HMO",
        "BCBS TX BlueChoice",
        "BCBS WY BlueSelect MRF",
        "Blue Cross",
        "Blue Cross CA Advantage PPO Preferred DirectAccess Plus",
        "Blue Cross CA Caifornia Care Large Group HMO",
        "Blue Cross CA Pathway X HMO",
        "Blue Cross CA Pathway X PPO",
        "Blue Cross CA PPO Prudent Buyer Individual",
        "Blue Cross CA PPO Prudent Buyer Large Group",
        "Blue Cross CA PPO Prudent Buyer Small Group",
        "Blue Cross CA Priority Select HMO",
        "Blue Cross CA Select HMO",
        "Blue Cross CA Select Plus HMO",
        "Blue Cross CA Select PPO",
        "Blue Cross CA Vivity",
        "Blue Shield CA 2017 I&F HMO - CoveredCA",
        "Blue Shield CA Access Plus HMO",
        "Blue Shield CA Access Plus Savenet",
        "Blue Shield CA Bronze 60 PPO SHOP",
        "Blue Shield CA Bronze Full PPO 4500",
        "Blue Shield CA Local Access Plus HMO",
        "Blue Shield CA Platinum Access + HMO 25",
        "Blue Shield CA Platinum Local Access + HMO 25",
        "Blue Shield CA PPO",
        "Blue Shield CA Silver 70 PPO",
        "Blue Shield CA Trio ACO HMO",
        "BS CA Platinum 90 PPO",
        "Capital BC Keystone Health Plan Central HMO",
        "Capital BC PPO",
        "CareFirst BlueChoice Advantage",
        "CareFirst BluePreferred PPO",
        "CareFirst Maryland POS",
        "CareSource Just4Me KY",
        "CDPHP HMO",
        "CDPHP New York State of Health - Individuals and Families",
        "CDPHP New York State of Health - Small Business",
        "CDPHP PPO",
        "Cigna",
        "CIGNA HMO",
        "CIGNA LocalPlus",
        "CIGNA Open Access Plus",
        "CIGNA PPO",
        "Cigna Southern CA Select",
        "CIGNA Southern CA Value",
        "CIGNA Total DPPO",
        "Colorado Choice Health Plans",
        "Connecticare Flex Connecticut",
        "Coventry Carelink - Carolinas HealthCare System Tier 1",
        "Coventry DE PPO",
        "Coventry FL Carelink HMO",
        "Coventry FL Employer Group HMO Open Access",
        "Coventry Health and Life IL PPO",
        "Coventry HealthAmerica HMO",
        "Coventry HealthAmerica PPO",
        "Coventry IL PPO",
        "Coventry MO HMO POS",
        "Coventry MO PPO",
        "Coventry PPO Platinum",
        "Coventry Southern Health PPO",
        "Coverntry FL Employer Group PPO",
        "Emblem Health Select Care",
        "Emblem Health Select Care Bronze",
        "Empire Blue Priority EPO",
        "Empire HMO",
        "Empire HMO Bronze Individual via Exchange",
        "Empire PPO",
        "Empire Prism EPO Blue Priority",
        "Encore Health Network",
        "Excellus BCBS Base Bronze Silver Gold Platinum Plans",
        "Excellus BluePPO",
        "Excellus HMOBlue",
        "Fidelis Care NY State of Health HBX",
        "First Health PPO",
        "Florida Blue BlueCare HMO",
        "Florida Blue BlueOptions",
        "Geising Mrktplace Plans",
        "Geisinger Health Plan",
        "Guardian DentalGuard Preferred",
        "Health Alliance HMO/POS",
        "Health Alliance IL IA Public Mrktplace QHP Provider Directory",
        "Health Alliance PPO",
        "Health Net",
        "Health Net Ambetter/CommunityCare HMO",
        "Health Net AZ PPO HSA",
        "Health Net CA CommunityCare Network HMO",
        "Health Net CA HMO Employer Group",
        "Health Net CA HMO SmartCare",
        "Health Net CA HMO Whole Care Network",
        "Health Net CA Individual and Family PPO",
        "Health Net CA PPO",
        "Health Net CA Primary EPO",
        "Health Net EPO - PureCare One Small Business",
        "Health Net PureCare HSP Individual and Family Plans",
        "Health Net PureCare One EPO Individual and Family Plan",
        "Health Net Salud EPO",
        "Health Net SmarCare Small Group",
        "Health Net SmartCare Large Group",
        "Healthfirst NY HMO ABCD",
        "Healthfirst NY Silver Leaf",
        "HealthLink PPO",
        "Highmark Alliance Flex Blue",
        "Highmark Blue Cross Blue Shield Shared Cost 1500, a Multi-State Plan",
        "Highmark Community Blue Flex EPO",
        "Highmark Community Blue PPO",
        "Highmark Comprehensive Care Blue PPO 1500 MRF",
        "Highmark Comprehensive Care Flex Blue PPO 500 MRF",
        "Highmark Health Savings Blue PPO 1400 MRF",
        "Highmark KeystoneBlue",
        "Highmark PPOBlue",
        "Highmark Shared Cost Blue PPO 6000 MRF",
        "HMSA Preferred Provider Comp Med",
        "Humana",
        "Humana Choice POS",
        "Humana ChoiceCare Network PPO",
        "Humana National POS",
        "Kaiser Permanente",
        "LACare",
        "Medi-Cal",
        "Medicare CA",
        "Molina Mrktplace CA",
        "Most Insurance Plans Accepted",
        "Multiplan PPO",
        "MVP Preferred PPO",
        "NSLIG Careconnect",
        "Oscar Insurance CA",
        "Oscar Insurance NY",
        "Oxford Freedom",
        "Oxford Liberty",
        "Oxford Metro",
        "PHCS PPO",
        "PHCS PPO Kaiser",
        "PHP Select with Encircle",
        "PriorityHealth HMO",
        "PriorityHealth Priority PPO",
        "Sharp Health Blue Choice",
        "Sharp Health Gold Value",
        "Sharp Health Performance",
        "Sharp Health Premier",
        "UHC Choice Plus POS",
        "UHC Compass HMO",
        "UHC Navigate HMO",
        "UHC Navigate POS",
        "UHC Optimum Choice Preferred POS",
        "UHC Options PPO",
        "UHC SignatureValue Flex1",
        "UHC SignatureValue Flex2",
        "UHC SignatureValue Flex3",
        "UHC SignatureValue Focus",
        "UHC West SignatureValue Advantage HMO Value Network",
        "UHC West SignatureValue Alliance",
        "UHC West SignatureValue HMO",
        "UPMC PPO",
        "UPMC Premium Network Plans",
    ];
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        //upload from full list
        foreach ($this->companiesFromDoc as $company) {
            if (!\modules\account\models\ar\InsuranceCompany::find()->andWhere(['name' => $company])->exists()) {
                $model = (new \modules\account\models\ar\InsuranceCompany(['name' => $company]));
                $model->detachBehavior('timestamp');
                $model->detachBehavior('blameable');
                $model->save(false);
            } else {
                \yii\helpers\Console::output('Duplicate entry ' . $company);
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        return true;
    }
}
