<?php

return [
    'class' => 'common\components\UrlManager',
    'baseUrl' => '/backend',
    'b2bPath' => env('B2B_URL'),
    'hostInfo' => env('BACKEND_URL'),
    'enableStrictParsing' => true,
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'normalizer' => [
        'class' => 'yii\web\UrlNormalizer',
    ],
    'rules' => [
        '/' => 'site/index',
        '/login' => 'site/login',
        '/logout' => 'site/logout',
        '/accounts/<type:(patient|professional|admin|client|health-profile)>' => 'account/<type>/index',
        '/accounts/<type:(patient|professional|admin|client|health-profile)>/<action:.*>' => 'account/<type>/<action>',
        'tutor-pro-service' => '/account/tutor-pro-service/index',
        '/account/tutor-pro-service/<action:.*>' => 'account/tutor-pro-service/<action>',
        '/account/tutor-score/<action:.*>' => 'account/tutor-score/<action>',
        'enable-review/<id:\d+>' => 'account/professional/enable-review',
        'banned-review/<id:\d+>' => 'account/professional/disable-review',
        'log/<action:.*>' => '/log/<action>',
        'insurance-company/<action:.*>' => '/insurance-company/<action>',
        'automatch-subjects/<action:.*>' => '/automatch-subjects/<action>',
        'change-log/<action:.*>' => '/change-log/<action>',
        'api-log-request/<action:.*>' => 'api-log-request/<action>',
        '/cities-autocomplete' => 'site/cities-autocomplete',
        '/account/job/<action:.*>' => 'account/job/<action>',
        '/account/subject/<action:.*>' => 'account/subject/<action>',
        '/coefficients/<action:.*>' => 'coefficients/<action>',
        '/account/lesson/<action:.*>' => 'account/lesson/<action>',
        '/account/review/<action:.*>' => 'account/review/<action>',
        '/payment/transaction/<action:.*>' => 'payment/transaction/<action>',
        '/payment/transaction-enterprise/<action:.*>' => 'payment/transaction-enterprise/<action>',
        '/payment/transaction-enterprise/' => 'payment/transaction-enterprise/index',
        '/message-feed/messages' => '/chat/messages/index',
        '/chat/restrictions/<action:.*>' => '/chat/chat-restriction/<action>',
        '/chat/<action:.*>' => '/chat/default/<action>',
        'subject-feed' => 'account/data-search/index',
        '/account/data-search/<action:.*>' => 'account/data-search/<action>',
        '/labels/categories/<action:.*>' => 'labels/categories/<action>',
        '/labels/<action:.*>' => 'labels/labels/<action>',
        '/health-tests/<action:.*>' => 'health-test/<action>',
        '/symptoms/<action:.*>' => 'symptom/<action>',
        '/medical-conditions/<action:.*>' => 'medical-condition/<action>',
        '/health-goals/<action:.*>' => 'health-goal/<action>',
        '/autoimmune-diseases/<action:.*>' => 'autoimmune-disease/<action>',
        '/states/<action:.*>' => 'state/<action>',
        '/allergies/<action:.*>' => 'allergy/<action>',
        '/allergy-categories/<action:.*>' => 'allergy-category/<action>',
        '/lifestyle-diets/<action:.*>' => 'lifestyle-diet/<action>',
        '/education-collage/<action:.*>' => 'education-collage/<action>',
        '/leads/<action:.*>' => 'lead/<action>',
    ],
];
