version: '3.8'
services:
    php:
        image: registry.gitlab.com/eltex/winitclinic/winitclinic-api/php:8.0-fpm-alpine
#        build:
#            context: ./
#            dockerfile: .docker/Dockerfile_php
        volumes:
            - ./:/var/www/html/:delegated
            - ./.docker/tmp/yarn/:/home/user/.cache/yarn/
        environment:
            - GITHUB_API_TOKEN
            - PHP_ENABLE_XDEBUG
            - XDEBUG_CONFIG
            - PHP_IDE_CONFIG

    nginx:
        image: nginx:stable
        volumes:
            - ./:/var/www/html/:delegated
            - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.0.1:80:80"

    # Upgrade to 8.0 `docker-compose exec mysql mysql_upgrade -uroot -p`
    mysql:
        image: mysql:8.0
        command:
            - "--default-authentication-plugin=mysql_native_password"
        volumes:
            - ./.docker/tmp/mysql:/var/lib/mysql:delegated
            - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: db
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_PASSWORD: db

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        depends_on:
#            - mysql
#        links:
#            - mysql
#        ports:
#            - "81:80"
#        volumes:
#            - /sessions
#        environment:
#            PMA_HOST: mysql

#    elasticsearch:
#        image: registry.gitlab.com/eltex/winitclinic/winitclinic-api/elasticsearch:latest
##        build:
##            context: ./
##            dockerfile: .docker/Dockerfile_elasticsearch
#        ulimits:
#          memlock:
#            soft: -1
#            hard: -1
#        ports:
#            - "127.0.0.1:9200:9200"
#        volumes:
#            - ./.docker/tmp/elasticsearch:/usr/share/elasticsearch/data
#        environment:
#            - ES_JAVA_OPTS=-Xmx2g -Xms2g

    adminer:
        image: adminer
        depends_on:
            - mysql
        ports:
            - "127.0.0.1:82:8080"
        volumes:
            - ./.docker/adminer/adminer.css:/var/www/html/adminer.css
