<?php

/**
 * @OA\Schema(
 *   schema="HealthProfileGeneralModel",
 *   required={"firstName"},
 *   @OA\Property(
 *       property="firstName",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="lastName",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="birthday",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="phoneNumber",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="email",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="height",
 *       type="number",
 *   ),
 *   @OA\Property(
 *       property="weight",
 *       type="number",
 *   ),
 *   @OA\Property(
 *       property="gender",
 *       type="integer",
 *   ),
 *   @OA\Property(
 *       property="googlePlaceId",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="address",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="zipCode",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="maritalStatusId",
 *       type="integer",
 *   ),
 *   @OA\Property(
 *       property="educationLevelId",
 *       type="integer",
 *   ),
 *   @OA\Property(
 *       property="childrenCount",
 *       type="integer",
 *   ),
 *   @OA\Property(
 *       property="occupation",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="employer",
 *       type="string",
 *   ),
 *   @OA\Property(
 *       property="health",
 *       ref="#/components/schemas/HealthProfileHealthModel",
 *   ),
 *   @OA\Property(
 *       property="medical",
 *       ref="#/components/schemas/HealthProfileMedicalModel",
 *   )
 * )
 */
