<?php

/**
 * @OA\Schema(
 *   schema="ProfessionalProfileModel",
 *   @OA\Property(
 *      property="id",
 *      type="integer",
 *      description="id",
 *      example="1"
 *   ),
 *   @OA\Property(
 *      property="publicId",
 *      type="string",
 *      description="Public ID",
 *      example="VJnSaCkalcKzt4Z-FCJuqB5BZva0fFhF"
 *   ),
 *   @OA\Property(
 *      property="email",
 *      type="string",
 *      description="Email",
 *      example="test@gmail.com"
 *   ),
 *   @OA\Property(
 *      property="hasPhoto",
 *      type="integer",
 *      description="User has photo",
 *      example="0"
 *   ),
 *   @OA\Property(
 *       property="profile",
 *       ref="#/components/schemas/AccountProfileModel",
 *   ),
 *   @OA\Property(
 *       property="rate",
 *       ref="#/components/schemas/AccountRateModel",
 *   ),
 *   @OA\Property(
 *       property="rating",
 *       ref="#/components/schemas/AccountRatingModel",
 *   ),
 *   @OA\Property(
 *       property="reviews",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountReviewsModel"),
 *   ),
 *   @OA\Property(
 *       property="languages",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountLanguageModel"),
 *   ),
 *   @OA\Property(
 *       property="educations",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountEducationModel"),
 *   ),
 *   @OA\Property(
 *       property="certifications",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountRewardModel"),
 *   ),
 *   @OA\Property(
 *       property="healthTests",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountHealthTestModel"),
 *   ),
 *   @OA\Property(
 *       property="symptoms",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountSymptomModel"),
 *   ),
 *   @OA\Property(
 *       property="medicalConditions",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountMedicalConditionModel"),
 *   ),
 *   @OA\Property(
 *       property="autoimmuneDiseases",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountAutoimmuneDiseaseModel"),
 *   ),
 *   @OA\Property(
 *       property="healthGoals",
 *       type="array",
 *       @OA\Items(ref="#/components/schemas/AccountHealthGoalModel"),
 *   ),
 * )
 */
