<?php
/**
 * @var float $amount
 * @var string $date
 * @var string $address
 * @var string $ip
 */
?>
<div class="student-terms">
    <h4 class="text-center text-uppercase">Winitclinic, Inc.’s Terms of Use</h4>

    <h5>Section 1 - General Terms</h5>
    <p>HeyTutor, Inc. (“HeyTutor”) has created a digital platform that facilitates connections with tutors in a variety of subjects through a curated platform. These Terms of Use (“Terms”) shall govern your (“you” or “your” as used herein shall mean the customer or potential customer of HeyTutor) access or use of all aspects and components of the platform and shall apply to the customer as well as all students who receive tutoring as result of purchases made by the customer, including other students within the customer’s family; other students for whom the customer purchases tutoring, in the event the customer is different than the one(s) receiving the tutoring; and any authorized user of customer’s account. These Terms constitute a legal agreement between you and HeyTutor.
        HeyTutor reserves the right to modify or amend these Terms at any time without notice, including doing so electronically, and any such modification or amendment accepted or agreed to by customer, or customers continued use of the platform after being notified of modification or amendment of the Terms shall supersede any prior terms related to the subject matter hereof. If you do not agree to these terms, you may not use the platform.
        HeyTutor  reserves  the  right  to  refuse  service  to  anyone  for  any  reason  at  any  time.  You  understand  that  your  content  (not  including  credit  card  information),  may  be  transferred  unencrypted  and  involve  (a)  transmissions  over  various  networks;  and  (b)  changes  to  conform  and  adapt  to  technical  requirements  of  connecting  networks  or  devices.  Credit card  information  is  always  encrypted  during  transfer  over  networks.
        The  headings  used  in  this  agreement  are  included  for  convenience  only  and  will  not  limit  or  otherwise  affect  these  Terms.</p>
    <h5>Section 2 - Accuracy and Completeness of Information</h5>
    <p> HeyTutor is  not  responsible  if  information  made  available  on  its platform or website  is  not  accurate,  complete  or  current.  The  material  is  provided  for  general  information  only  and  should  not  be  relied  upon  or  used  as  the  sole  basis  for  making  decisions  without  consulting  primary,  more  accurate,  more  complete  or  timelier  sources  of  information.  Any reliance  on  the  material is  at  your  own  risk.  This site or platform may  contain  certain  historical  information.  Historical  information,  necessarily,  is  not  current  and  is  provided  for  your  reference  only.  HeyTutor  reserves  the  right  to  modify  the  contents  of  this  site  or our platform at  any  time,  but  we  have  no  obligation  to  update  any  information  on  our  site.  You  agree  that  it  is  your  responsibility  to  monitor  changes  to  our  site and platform.</p>
    <h5>Section 3 - Guarantee and Refund Policy</h5>
    <p>
        HeyTutor’s Guarantee: If after the initial session you are not satisfied with the tutor chosen through HeyTutor’s platform, please contact HeyTutor for assistance selecting a new tutor.  The session with the new tutor shall be without charge (for the same length as the initial session). If you are still not satisfied after your second session, you will receive a full refund of all sessions that you have ordered and paid for.
        Cancellation of Session: If you need to cancel a session, HeyTutor requires that you give your tutor at least 24-hours’ written notice prior to the scheduled tutoring session. If you give less than 24-hours’ written notice prior to the session, 1 hour of tutoring will be deducted from your account balance by the tutor. If you do not give any notice of cancellation or are not otherwise available within 10 minutes of your scheduled start time, you will be charged by the tutor for the full tutoring session.
        Chaperone: A legal guardian or an approved chaperone of at least 21 years of age for any minor student must execute these Terms and be present for tutoring in order for tutoring services to be performed for a minor student, unless the session occurs in a public setting. If a guardian is not present with a minor student within 10 minutes of the scheduled start time, for a session that is not in public, the session will be considered cancelled and you will be charged for the full session.
    </p>
    <h5>Section 4 - Non-Solicitation and Trade Secret Policy</h5>
    <p>HeyTutor has expended substantial resources creating the platform and having qualified tutors available on it to provide you and/or the student(s) with an individualized tutoring experience. Because of this investment by HeyTutor, it is critical to HeyTutor’s business to prohibit customers from soliciting or contracting with tutors outside the platform that the customers were introduced to, directly or indirectly, through the platform.  Accordingly, you and the student(s) using tutors obtained through HeyTutor’s platform agree not to solicit, attempt to solicit, or contract with a HeyTutor’s contracted tutors, directly or indirectly, for a period of two (2) years following the final tutoring session with any tutor obtained through HeyTutor’s platform except through HeyTutor’s platform or with the express written consent of HeyTutor.
        You acknowledge that HeyTutor has a valid contract and/or business expectancy with the contracted tutors who are subject to their own two (2) year non-solicitation provision regarding HeyTutor’s customers. Violating the non-solicitation provision, or failing to notify HeyTutor in the event you have reason to believe a tutor is actually or attempting to do so, also constitutes tortious interference with HeyTutor’s contract with the tutor for which you may be liable to HeyTutor for monetary damages and/or equitable relief.  In the event of a violation, the Parties acknowledge that the actual costs and resulting damages (lost productivity, increased operating costs, lost advertising costs, lost customer acquisition costs, customer lifetime value, etc.) are difficult to ascertain, calculate, and foresee. You also hereby agree and acknowledge that HeyTutor’s list of tutors it works with is proprietary information and a protected trade secret under California law.</p>
    <h5>Section 5 - Legal Status of Tutors</h5>
    <p>The tutors on HeyTutor’s platform are independent contractors, not employees, with their own tutoring styles and methods. Tutors’ credentials have been reviewed by HeyTutor. You are free to select whichever tutor from the platform, provided the tutor agrees to your selected preferences including the materials to be used as well as the date, time, and location of the tutoring sessions. You can choose to select different tutors at any time from the platform, including after the first session and pursuant to HeyTutor’s Guarantee.
        In addition to your ability to change tutors at any time, you also have the right to a refund in accordance with HeyTutor’s Guarantee. While you can work with HeyTutor to select another tutor through the platform at any time or do so yourself, HeyTutor relies upon you to make such a request because you will be involved in the tutoring process and will know what you hope to accomplish from the tutor.  Similarly, if you are not seeing the results you are looking for or particular outcomes you desire, you are free to request a new tutor through the platform and HeyTutor will assist with matching you with another tutor.  Matching you with a new tutor is the only thing HeyTutor can do if you are unsatisfied with the results, outcomes, or tutor’s services (other than to the extent the guarantee or refund apply).</p>
    <h5>Section 6 - Minimum Billing</h5>
    <p>While the length of each session shall be determined between you and the tutor, HeyTutor reserves the right to bill you for certain minimum session lengths based upon the particular subject, grade level, tutor availability, or other factors, as specifically indicated at the time of purchase.</p>
    <h5>Section 7 - Recorded Tutoring Sessions</h5>
    <p>HeyTutor records all sessions conducted on the platform, unless you elect in writing not to do so. In order to opt out of session recording, you must de-select recording of sessions as a preference generally on the online account page for the customer or the customer or student may opt out of recording the particular session to be recorded at the beginning of that session (and any subsequent session(s)). By agreeing to these Terms, you consent to such recording and do so on behalf of any authorized user of customer’s account that opts to have the session recorded. Recordings are made solely for educational purposes and shall remain the sole and exclusive property of HeyTutor. Recordings will not be available to tutors and can only be accessed by a customer or authorized user of customer’s account through his, her, or its account on the platform or by an authorized representative of HeyTutor solely for quality assurance and technical purposes. Recordings should be available within 24 hours of the session. HeyTutor retains sole discretion regarding the availability of recordings to customers and authorized users and will endeavor to provide notice to customer in the event recordings will be intentionally deleted by HeyTutor. Customer agrees that session recordings may not be downloaded, broadcast, or otherwise reproduced in any form, for any reason, and shall be responsible for any violation by an authorized user of customer’s account.</p>
    <h5>Section 8 - Conversion of Tutoring Hours</h5>
    <p>There are different rates for different tutoring types, including but not limited to academic (including grade levels), test prep, in-person, online, and instant tutoring. HeyTutor will automatically convert your tutoring hours based upon the use of a different tutoring type.  Conversion of hours will be done automatically at the then current rate when a different tutoring type is requested or used.  This provides you the flexibility to pursue whatever tutoring type you choose.</p>
    <h5>Section 9 - Confidentiality Clause</h5>
    <p>You may obtain confidential information and or trade secrets of HeyTutor during the course of your use of HeyTutor’s platform. This information includes, but is not limited to, contractual, technical, pricing, marketing, product, or other valuable information. You agree to hold such information in strict confidence.  All right, title, and interest in HeyTutor’s confidential information shall remain with HeyTutor.  Confidential information shall not include information you possessed prior to your access to information through HeyTutor’s platform, that becomes generally known to the public (without violation of these Terms), or you obtained from a third party who was not legally prohibited from disclosing it, that you independently developed without the use of HeyTutor’s confidential information.</p>
    <h5>Section 10 - Customer Content Release</h5>
    <p>HeyTutor may allow you to submit, upload, publish, or otherwise make available through HeyTutor’s platform certain content.  While any content provided by you remains your property, you hereby grant HeyTutor an irrevocable, perpetual, transferable, non-exclusive, fully paid-up, royalty-free, worldwide license (sub licensable through multiple tiers) to: (a) use, copy, distribute, reproduce, modify, create derivative works of, adapt, publish, translate, publicly perform, and publicly display such content (or any modification thereto), in whole or in part, in any format, medium or application now known or later developed, and (b) use (and permit others to use) such content in any manner and for any purpose (including, but not limited to, commercial purposes) that HeyTutor deems appropriate in its sole discretion (including, but not limited to, incorporating such content (or any modification thereto), in whole or in part, into any technology, product, or service.</p>
    <h5>Section 11 - Restrictions</h5>
    <p>You shall not: (i) remove any copyright, trademark, or other proprietary notices from the platform; (ii) transfer, reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, display publicly, perform publicly, transmit, stream, broadcast, or otherwise exploit the platform, except as expressly permitted by HeyTutor; (iii) decompile, disassemble, or reverse engineer the platform, unless permitted by law; (iv) link to, or frame any portion of the platform; (v) cause or launch any program or script for the purpose of scraping, indexing, or surveying any portion of the platform or hindering the functionality or operation of the platform; or (vi)  attempt to gain unauthorized access to or impair any aspect of the platform’s systems or networks.</p>
    <h5>Section 12 – Optional Tools</h5>
    <p>HeyTutor  may  provide  you  with  access  to  third-party  tools  over  which  HeyTutor  neither  monitors  nor  has  any  control  nor  input.  You  acknowledge  and  agree  that  HeyTutor  provides  access  to  such  tools  ”as  is”  and  “as  available” without  any  warranties,  representations  or  conditions  of  any  kind  and  without  any  endorsement.  HeyTutor  shall  have  no  liability  whatsoever  arising  from  or  relating  to  your  use  of  optional  third-party  tools.  Any  use  by  you  of  optional  tools  offered  through  the  site  is  entirely  at  your  own  risk  and  discretion  and  you  should  ensure  that  you  are  familiar  with  and  approve  of  the  terms  on  which  tools  are  provided  by  the  relevant  third-party  provider(s).  HeyTutor  may  also,  in  the  future,  offer  new  services  and/or  features  through  the  website or platform  (including,  the  release  of  new  tools  and  resources).  Such  new  features  and/or  services  shall  also  be  subject  to  these  Terms  of  Service.</p>
    <h5>Section 13 – Third Party Links</h5>
    <p>Certain  content,  products  and  services  available  via  our  platform  may  include  materials  from  third-parties.  Third-party  links  on  this  site or platform may  direct  you  to  third-party  websites  that  are  not  affiliated  with  HeyTutor  .  HeyTutor  is  not  responsible  for  examining  or  evaluating  the  content  or  accuracy  and  HeyTutor  does  not  warrant  and  will  not  have  any  liability  or  responsibility  for  any  third-party  materials  or  websites,  or  for  any  other  materials,  products,  or  services  of  third-parties.  HeyTutor  is  not  liable  for  any  harm  or  damages  related  to  the  purchase  or  use  of  goods,  services,  resources,  content,  or  any  other  transactions  made  in  connection  with  any  third-party  websites.  Please  review  carefully  the  third-party's  policies  and  practices  and  make  sure  you  understand  them  before  you  engage  in  any  transaction.  Complaints,  claims,  concerns,  or  questions  regarding  third-party  products  should  be  directed  to  the  third-party.</p>
    <h5>Section 14 – Errors, Inaccuracies, and Omissions</h5>
    <p>Occasionally  there  may  be  information  on  HeyTutor’s platform or  site  that  contains  typographical  errors,  inaccuracies  or  omissions  that  may  relate  to  product  or  service  descriptions,  pricing,  promotions,  offers,  product  shipping  charges,  transit  times  and  availability.  HeyTutor reserves  the  right  to  correct  any  errors,  inaccuracies  or  omissions,  and  to  change  or  update  information  or  cancel  orders  if  any  information is  inaccurate  at  any  time  without  prior  notice  (including  after  you  have  submitted  your  order).  HeyTutor undertakes  no  obligation  to  update,  amend  or  clarify  information  in  the  Service  or  on  any  related  website,  including  without  limitation,  pricing  information,  except  as  required  by  law.  No  specified  update  or  refresh  date  applied should  be  taken  to  indicate  that  all  information has  been  modified  or  updated.</p>
    <h5>Section 15- Prohibited Uses</h5>
    <p>In  addition  to  other  prohibitions  as  set  forth  in  the  Terms  of  Service,  you  are  prohibited  from  using  the  site or platform  or  their  content:  (a)  for  any  unlawful  purpose;  (b)  to  solicit  others  to  perform  or  participate  in  any  unlawful  acts;  (c)  to  violate  any  international,  federal,  provincial  or  state  regulations,  rules,  laws,  or  local  ordinances;  (d)  to  infringe  upon  or  violate  our  intellectual  property  rights  or  the  intellectual  property  rights  of  others;  (e)  to  harass,  abuse,  insult,  harm,  defame,  slander,  disparage,  intimidate,  or  discriminate  based  on  gender,  sexual  orientation,  religion,  ethnicity,  race,  age,  national  origin,  or  disability;  (f)  to  submit  false  or  misleading  information;  (g)  to  upload  or  transmit  viruses  or  any  other  type  of  malicious  code  that  will  or  may  be  used  in  any  way  that  will  affect  the  functionality  or  operation  of  the  Service  or  of  any  related  website,  other  websites,  or  the  Internet;  (h)  to  collect  or  track  the  personal  information  of  others;  (i)  to  spam,  phish,  pharm,  pretext,  spider,  crawl,  or  scrape;  (j)  for  any  obscene  or  immoral  purpose;  or  (k)  to  interfere  with  or  circumvent  the  security  features  of  the  platform,  other  websites,  or  the  Internet.  HeyTutor  reserves  the  right  to  terminate  your  use  of  the  platform  or  any  related  website  for  violating  any  of  the  prohibited  uses.</p>
    <h5>Section 16- Limitation of Liability</h5>
    <p>HeyTutor  does  not  guarantee,  represent  or  warrant  that  your  use  of  our  platform  will  be  uninterrupted,  timely,  secure,  or  error-free.  HeyTutor  does  not  warrant  that  the  results  that  may  be  obtained  from  the  use  of  the  platform  will  be  accurate  or  reliable.  You  agree  that  from  time  to  time  HeyTutor  may  remove  the  platform  for  indefinite  periods  of  time  or  cancel  the  platform  at  any  time,  without  notice  to  you.  You  expressly  agree  that  your  use  of,  or  inability  to  use,  the  platform  is  at  your  sole  risk.  The  platform  and  all  products  and  services  delivered  to  you  through  the  platform  are  (except  as  expressly  stated  by  us)  provided  'as  is'  and  'as  available'  for  your  use,  without  any  representation,  warranties  or  conditions  of  any  kind,  either  express  or  implied,  including  all  implied  warranties  or  conditions  of  merchantability,  merchantable  quality,  fitness  for  a  particular  purpose,  durability,  title,  and  non-infringement.  In  no  case  shall  HeyTutor,  our  directors,  officers,  employees,  affiliates,  agents,  contractors,  interns,  suppliers,  service  providers  or  licensors  be  liable  for  any  injury,  loss,  claim,  or  any  direct,  indirect,  incidental,  punitive,  special,  or  consequential  damages  of  any  kind,  including,  without  limitation  lost  profits,  lost  revenue,  lost  savings,  loss  of  data,  replacement  costs,  or  any  similar  damages,  whether  based  in  contract,  tort  (including  negligence),  strict  liability  or  otherwise,  arising  from  your  use  of  any  of  the  platform  or  any  products  procured  using  the  platform,  or  for  any  other  claim  related  in  any  way  to  your  use  of  the  platform  or  any  product,  including,  but  not  limited  to,  any  errors  or  omissions  in  any  content,  or  any  loss  or  damage  of  any  kind  incurred  as  a  result  of  the  use  of  the  platform  or  any  content  (or  product)  posted,  transmitted,  or  otherwise  made  available  via  the  platform  ,  even  if  advised  of  their  possibility.
        Because  some  states  or  jurisdictions  do  not  allow  the  exclusion  or  the  limitation  of  liability  for  consequential  or  incidental  damages,  in  such  states  or  jurisdictions,  HeyTutor’s  liability  shall  be  limited  to  the  maximum  extent  permitted  by  law.</p>
    <h5>Section 17 – Indemnification</h5>
    <p>You  agree  to  indemnify,  defend  and  hold  harmless HeyTutor  and  our  parent,  subsidiaries,  affiliates,  partners,  officers,  directors,  agents,  contractors,  licensors,  service  providers,  subcontractors,  suppliers,  interns  and  employees,  harmless  from  any  claim  or  demand,  including  reasonable  attorneys’  fees,  made  by  any  third-party  due  to  or  arising  out  of  your  breach  of  these  Terms  of  Service  or  the  documents  they  incorporate  by  reference,  or  your  violation  of  any  law  or  the  rights  of  a  third-party.</p>
    <h5>Section 18 – Severability</h5>
    <p>In  the  event  that  any  provision  of  these  Terms  of  Service  is  determined  to  be  unlawful,  void  or  unenforceable,  such  provision  shall  nonetheless  be  enforceable  to  the  fullest  extent  permitted  by  applicable  law,  and  the  unenforceable  portion  shall  be  deemed  to  be  severed  from  these  Terms  of  Service,  such  determination  shall  not  affect  the  validity  and  enforceability  of  any  other  remaining  provisions.</p>
    <h5>Section 19 - Arbitration</h5>
    <p>In order to expedite and control the cost of disputes, you and HeyTutor agree that any legal or equitable claim, other than a claim under the Section titled “Non-Solicitation,” relating to this Agreement, any addendum, the use of the platform, or the tutoring obtained from the platform (referred to as a “Claim”), will be resolved as follows:  If a Claim cannot be resolved informally, any Claim asserted will be resolved only by binding arbitration. ARBITRATION MEANS THAT YOU WAIVE YOUR RIGHT TO JURY TRIAL. The arbitration will be conducted by one arbitrator who is a member of the American Arbitration Association (“AAA”) and will be governed by the Consumer Arbitration Rules of the AAA. The arbitration will be held in Los Angele, California or as mutually agreed between the parties and the arbitrator will apply California substantive law, or federal law as applicable, in all respects.  The arbitrator shall have all authority to determine the arbitrability of any claim and enter a final binding judgment at the conclusion of any proceedings.  Any final judgment may be appealed only on the grounds of improper bias or improper conduct of the arbitrator.  If you decide to initiate arbitration, you will have to submit a demand for arbitration with a filing fee to https://www.adr.org.  HeyTutor agrees to reimburse you for the filing fee; however, all other fees related to the arbitration, including the fees of the arbitrator, attorneys’ fees, arbitration expenses, etc. shall be determined by the arbitrator in accordance with the AAA rules.</p>
    <h5>Section 20 - Governing Law</h5>
    <p>The laws of the State of California shall govern these Terms, the construction of its terms, and the interpretation of the rights and duties of the parties hereto, as well as any claim that may arise between you and HeyTutor, without regard to any conflict of law provisions.</p>

    <div class="text-left fw-semi">
        <p><b>Amount paid: $<?=$amount?></b></p>
        <p><b>Date: <?=$date?></b></p>
        <p><b>Student address: <?=$address?></b></p>
        <p><b>Student ip-address: <?=$ip?></b></p>
    </div>
</div>
